In [1]:
import pandas as pd

In [109]:
import string

In [104]:
import nltk

In [6]:
import sklearn

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
from sklearn.model_selection import train_test_split

In [105]:
stopwords = nltk.corpus.stopwords.words('portuguese')

In [2]:
data_frame_original = pd.read_csv("./imdb-reviews-pt-br.csv")
data_frame_original.head()

,id,text_en,text_pt,sentiment
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg

In [4]:
data_frame_original['classificacao'] = data_frame_original['sentiment'].replace(['neg', 'pos'], [0, 1])

In [5]:
data_frame_original

,id,text_en,text_pt,sentiment,classificacao
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg,0
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg,0
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg,0
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg,0
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg,0
...,...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos,1
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos,1
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos,1
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos,1
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos,1

In [113]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [116]:
def limpar_texto( texto ):
    return texto.lower().translate(str.maketrans("", "", string.punctuation))

In [117]:
# limpar_texto("Como a média de votos era muito baixa, e o fat..")

'como a média de votos era muito baixa e o fat'

In [122]:
def remover_stop_word( texto ): 
    texto_limpo = limpar_texto( texto )
    tokens = nltk.tokenize.word_tokenize(texto_limpo, language='portuguese')
    lista_limpa = []
    for token in tokens:
        if token not in stopwords:
            lista_limpa.append( token )
    return " ".join(lista_limpa)

In [123]:
data_frame_original["text_pt_no_stops"] = data_frame_original['text_pt'].apply(remover_stop_word)

In [124]:
data_frame_original

,id,text_en,text_pt,sentiment,classificacao,text_pt_no_stops
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg,0,vez sr costner arrumou filme tempo necessário ...
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg,0,exemplo motivo maioria filmes ação mesmos gené...
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg,0,primeiro tudo odeio raps imbecis poderiam agir...
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg,0,beatles puderam escrever músicas todos gostass...
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg,0,filmes fotos latão palavra apropriada verdade ...
...,...,...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos,1,média votos baixa fato funcionário locadora ac...
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos,1,enredo algumas reviravoltas infelizes inacredi...
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos,1,espantado forma filme maioria outros média 5 e...
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos,1,christmas together realmente veio antes tempo ...
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos,1,drama romântico classe trabalhadora diretor ma...

In [125]:
vetorizador = CountVectorizer(max_features=1000)

In [126]:
bag_of_word = vetorizador.fit_transform(data_frame_original['text_pt_no_stops'])

In [127]:
bag_of_word.shape

(49459, 1000)

In [128]:
vocabulario = vetorizador.get_feature_names_out()
len(vocabulario)

1000

In [129]:
one_hot = pd.DataFrame.sparse.from_spmatrix(bag_of_word, columns=vetorizador.get_feature_names_out())

In [130]:
one_hot

,10,12,15,20,30,50,60,70,80,90,...,água,época,óbvio,ótima,ótimo,última,último,últimos,única,único
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49456,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
49457,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
49458,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [133]:
x_train, x_test, y_train, y_test = train_test_split(one_hot, data_frame_original['classificacao'], random_state=50)

In [134]:
x_train

,10,12,15,20,30,50,60,70,80,90,...,água,época,óbvio,ótima,ótimo,última,último,últimos,única,único
14334,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5620,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23663,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28667,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3424,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48417,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
22637,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42891,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
38368,0,0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,0
14000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
# x_train = one_hot[0:37093]
# y_train = data_frame_original['classificacao'][0:37093]

In [79]:
# x_test = one_hot[37093:]
# y_test = data_frame_original['classificacao'][37093:]

In [135]:
reg_log = LogisticRegression()

In [136]:
reg_log.fit(x_train, y_train)

D:\usr\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [137]:
acuracia = reg_log.score(x_test, y_test)

In [139]:
acuracia

0.8489284270117267

In [140]:
novo_vetorizador = CountVectorizer(vocabulary=vocabulario)

In [141]:
bow_predict = novo_vetorizador.fit_transform(['caramba gastei horas assitindo este filme e ele é muito legal'])

In [142]:
one_hot_predict = pd.DataFrame.sparse.from_spmatrix(bow_predict, columns=vocabulario)

In [143]:
one_hot_predict

,10,12,15,20,30,50,60,70,80,90,...,água,época,óbvio,ótima,ótimo,última,último,últimos,única,único
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [144]:
reg_log.predict(one_hot_predict)

array([0], dtype=int64)